version: '3.4'

services:
  techskills.api:
    image: ${DOCKER_REGISTRY-}techskillsapi
    build:
      context: .
      dockerfile: TechSkills.API/Dockerfile
    depends_on:
        - techskills.database


  techskills.seq:
    container_name: techskills-seq
    image: datalust/seq:2024
    environment:
        - ACCEPT_EULA=Y  
    ports:
        - "5341:5341"
        - "8081:80" 
    


  techskills.database: 
    container_name: techskills-database
    image: postgres:16
    environment:
        - POSTGRES_PASSWORD=s3cret_passWord
        - POSTGRES_USER=ilnazix
        - POSTGRES_DB=techskills_db
    volumes:
        - techskills:/var/lib/postgresql/data
    ports: 
        - "5432:5432"
        

volumes:
    techskills: 
        name: "techskills"
