version: '3.4'

services:
  techskills.api:
    image: ${DOCKER_REGISTRY-}techskillsapi
    build:
      context: .
      dockerfile: TechSkills.API/Dockerfile
    depends_on:
        - database
  database: 
    container_name: courses_db
    image: postgres:16
    environment:
        - POSTGRES_PASSWORD=s3cret_passWord
        - POSTGRES_USER=ilnazix
        - POSTGRES_DB=techskills_db
    volumes:
        - techskills:/var/lib/postgresql/data
    ports: 
        - "5432:5432"
        

volumes:
    techskills: 
        name: "techskills"
